title: Chuangjian Liang's Homepage
page-top-title: Chuangjian Liang
top-section-bg-text: Mechanical Engineering
home-subtitle: Chuangjian Liang&ensp;|&ensp;梁创楗
copyright-text: '&copy; Chuangjian Liang 2023-2024. All Rights Reserved.'
